### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by bryanaka** [BryanCrotaz/ember-tracked-effects-placeholder#1]
In an application, I run `ember install ember-tracked-effects-placeholder`, it installs successfully, but the import then fails saying it can't find `tracked-toobox`

I think `tracked-toolbox` may not be set as a dependency correctly. Once I added it as an explicit dependency, it worked fine.

**Comment by BryanCrotaz** [comment]
You are right. Try v1.1.2
